return {
    faceColor       = {0.6, 0.3, 0.8},
    numLanes        = 4,
    cardSpeed       = 40,
    maxHP           = 20,
    waveIntervalMin = 10.0,
    waveIntervalMax = 15.0,
    waveSizeMin     = 1,
    waveSizeMax     = 3,
    shieldChance    = 0,
    minShield       = 2,
    maxShield       = 3,
    fastChance      = 0,
    startWithChance = 0.25,
    endWithChance   = 0.25,
    infixChance     = 0.2,
    bombChance      = 0,
    chainChance     = 0,
    chainSizeMin    = 0,
    chainSizeMax    = 0,
}
