return {
    faceColor       = {0.3, 0.6, 0.9},
    numLanes        = 4,
    cardSpeed       = 40,
    maxHP           = 10,
    waveIntervalMin = 10.0,
    waveIntervalMax = 15.0,
    waveSizeMin     = 3,
    waveSizeMax     = 4,
    shieldChance    = 0.8,
    minShield       = 1,
    maxShield       = 2,
    fastChance      = 0,
    startWithChance = 0,
    endWithChance   = 0,
    infixChance     = 0,
    bombChance      = 0,
    chainChance     = 0,
    chainSizeMin    = 0,
    chainSizeMax    = 0,
}
