return {
    faceColor       = {0.9, 0.5, 0.1},
    numLanes        = 4,
    cardSpeed       = 50,
    maxHP           = 12,
    waveIntervalMin = 4.0,
    waveIntervalMax = 5.0,
    waveSizeMin     = 1,
    waveSizeMax     = 4,
    shieldChance    = 0,
    minShield       = 2,
    maxShield       = 3,
    fastChance      = 0,
    startWithChance = 0,
    endWithChance   = 0,
    infixChance     = 0,
    bombChance      = 0.75,
    chainChance     = 0,
    chainSizeMin    = 0,
    chainSizeMax    = 0,
}
