return {
    faceColor       = {0.8, 0.2, 0.1},
    numLanes        = 7,
    cardSpeed       = 40,
    maxHP           = 40,
    waveIntervalMin = 7.0,
    waveIntervalMax = 10.0,
    waveSizeMin     = 3,
    waveSizeMax     = 7,
    shieldChance    = 0.2,
    minShield       = 1,
    maxShield       = 1,
    fastChance      = 0.2,
    startWithChance = 0.1,
    endWithChance   = 0.1,
    infixChance     = 0.1,
    bombChance      = 0.1,
    chainChance     = 0.7,
    chainSizeMin    = 2,
    chainSizeMax    = 3,
}
