return {
    faceColor       = { 0.4, 0.2, 0.6 },
    numLanes        = 7,
    cardSpeed       = 40,
    waveIntervalMin = 6.0,
    waveIntervalMax = 9.0,
    waveSizeMin     = 1,
    waveSizeMax     = 7,
    shieldChance    = 0.1,
    minShield       = 1,
    maxShield       = 2,
    fastChance      = 0.1,
    startWithChance = 0.1,
    endWithChance   = 0.1,
    infixChance     = 0.05,
    bombChance      = 0.05,
    chainChance     = 0.4,
    chainSizeMin    = 2,
    chainSizeMax    = 3,
}
