return {
    faceColor       = {0.85, 0.65, 0.5},
    numLanes        = 4,
    cardSpeed       = 45,
    maxHP           = 25,
    waveIntervalMin = 4.0,
    waveIntervalMax = 5.0,
    waveSizeMin     = 3,
    waveSizeMax     = 4,
    shieldChance    = 0,
    minShield       = 2,
    maxShield       = 3,
    fastChance      = 0.8,
    startWithChance = 0,
    endWithChance   = 0,
    infixChance     = 0,
    bombChance      = 0,
    chainChance     = 0,
    chainSizeMin    = 0,
    chainSizeMax    = 0,
}
